### ISSUE TITLE
Algebra - Mean, Median, Mode

### ISSUE THREAD

**Issue by mathincubator** [mathincubator/mathlib#1]
Implement the Algebra - Mean, Median, Mode definition documented in here:
 http://ec2-34-200-244-39.compute-1.amazonaws.com/boards/5/topics/5/

**Comment by mathincubator** [comment]
Jay:        Mean
Frankie: Mode
Carole:  Median

**Comment by mathincubator** [comment]
Two weeks for each iteration

**Comment by caroleluo22** [comment]
checked in median code @Jay8600 improve the mean code

**Comment by mathincubator** [comment]
Carole: Please also look into harmonic mean.

**Comment by caroleluo22** [comment]
http://ec2-34-200-244-39.compute-1.amazonaws.com/boards/5/topics/17/

**Comment by mathincubator** [comment]
Frankie need to implement the mode code

**Comment by warrior2278** [comment]
finished code for mode too, can nwo close issue
