### ISSUE TITLE
Algebra - Arithmetic Sequences

### ISSUE THREAD

**Issue by mathincubator** [mathincubator/mathlib#2]
Implement the definition documented in here: http://ec2-34-200-244-39.compute-1.amazonaws.com/boards/5/topics/6/

**Comment by mathincubator** [comment]
Carole: Arithmetic sequence

**Comment by andrewhe01** [comment]
Read the theory havent coded yet

**Comment by mathincubator** [comment]
Andrew and Bryan have done the coding. Code merged. Close this issue
