### ISSUE TITLE
Exponent tutorial

### ISSUE THREAD

**Issue by mathincubator** [mathincubator/mathlib#44]
Create exponent formulas related tutorials. 
http://ec2-34-200-244-39.compute-1.amazonaws.com/boards/5/topics/36/

**Comment by warrior2278** [comment]
Will be doing code for product rule and then quotient rule.

**Comment by warrior2278** [comment]
finished my tutorials, waiting for jay to close issue.

**Comment by warrior2278** [comment]
jay needs to catch up a bit
